name: 'Terraform apply'
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: The environment to deploy against.
        type: string
        default: intg
      project:
        required: true
        description: The project to run this for
        type: choice
        options:
          - tdr
          - dr2
permissions:
  id-token: write
  contents: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: nationalarchives/dr2-github-actions/.github/actions/set-terraform-secret-names@create-generic-apply-job
        with:
          project: ${{ github.event.inputs.project }}
          environment: ${{ github.event.inputs.environment }}
  apply:
    uses: nationalarchives/dr2-github-actions/.github/workflows/terraform_apply.yml@create-generic-apply-job
    needs: setup
    with:
      repo-name: tna-custodian
      environment: ${{ github.event.inputs.environment }}
      working-directory: terraform
      project: ${{ github.event.inputs.project }}
    secrets:
      WORKFLOW_TOKEN: ${{ secrets[needs.setup.outputs.workflow-token-var] }}
      ACCOUNT_NUMBER: ${{ secrets[needs.setup.outputs.account-number-secret] }}
      SLACK_WEBHOOK: ${{ secrets[needs.setup.outputs.slack-webhook-var] }}
      TERRAFORM_ROLE: ${{ secrets[needs.setup.outputs.terraform-role-var] }}
      STATE_BUCKET: ${{ secrets[needs.setup.outputs.state-bucket-var] }}
      DYNAMO_TABLE: ${{ secrets[needs.setup.outputs.dynamo-table-var] }}
  custodian:
    environment: ${{ github.event.inputs.project }}-${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    needs:
      - setup
      - apply
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets[format('{0}_WORKFLOW_PAT', needs.setup.outputs.project-upper)] }}
      - name: Configure AWS credentials for Cloud Custodian
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets[needs.setup.outputs.custodian-role-var] }}
          aws-region: eu-west-2
          role-session-name: CustodianRole
      - run: |
          pip install ruamel.yaml c7n c7n-mailer c7n-guardian --ignore-installed six
          cd accounts
          ../custodian/scripts/deploy-custodian.sh ${{ needs.setup.outputs.project-upper }} ${{ github.event.inputs.environment }} ${{ steps.set-environment-names.outputs.email }} ${{ secrets[format('{0}_MANAGEMENT_ACCOUNT', needs.setup.outputs.project-upper)] }}
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        with:
          message: |
            Cloud Custodian deployed to ${{ github.event.inputs.environment }} AWS account
          slack-url: ${{ secrets[format('{0}_SLACK_WEBHOOK', needs.setup.outputs.project-upper)] }}
