name: 'Terraform check'
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: nationalarchives/dr2-github-actions/.github/workflows/terraform_check.yml@main
    with:
      working-directory: terraform
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.DR2_WORKFLOW_PAT }}
      STATE_BUCKET: ${{ secrets.DR2_MGMT_STATE_BUCKET }}
      DYNAMO_TABLE: ${{ secrets.DR2_MGMT_DYNAMO_TABLE }}
      TERRAFORM_ROLE: ${{ secrets.DR2_INTG_TERRAFORM_ROLE }}
