name: 'Terraform check'
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: nationalarchives/dr2-github-actions/.github/workflows/terraform_check.yml@main
    with:
      working-directory: terraform
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.TDR_MANAGEMENT_ACCOUNT }}
      WORKFLOW_TOKEN: ${{ secrets.TDR_WORKFLOW_PAT }}
      STATE_BUCKET: ${{ secrets.TDR_MGMT_STATE_BUCKET }}
      DYNAMO_TABLE: ${{ secrets.TDR_MGMT_DYNAMO_TABLE }}
