name: 'Terraform check'
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: nationalarchives/tdr-github-actions/.github/workflows/terraform_check.yml@main
    with:
      working-directory: 'terraform'
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.TDR_MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.TDR_WORKFLOW_PAT }}
